### ISSUE TITLE
Compilation warnings: default_firmware.ino

### ISSUE THREAD

**Issue by matsujirushi** [Seeed-Studio/Wio_Tracker_1110_Examples#20]
### default_firmware.ino

- [x] default_firmware.ino:235:16: warning: format '%d' expects argument of type 'int', but argument 2 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
- [x] default_firmware.ino:246:21: warning: unused variable 'counter' [-Wunused-variable]
- [x] default_firmware.ino:275:13: warning: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
- [x] default_firmware.ino:275:13: warning: format '%u' expects argument of type 'unsigned int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
- [x] default_firmware.ino:275:13: warning: format '%u' expects argument of type 'unsigned int', but argument 4 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
- [x] default_firmware.ino:323:17: warning: format '%d' expects argument of type 'int', but argument 2 has type 'int32_t' {aka 'long int'} [-Wformat=]
- [x] default_firmware.ino:323:17: warning: format '%d' expects argument of type 'int', but argument 3 has type 'int32_t' {aka 'long int'} [-Wformat=]
- [x] default_firmware.ino:246:21: warning: 'counter' defined but not used [-Wunused-variable]

### LBM_WM1110

- [ ] wifi_middleware.c:711:9: warning: 'memcpy' forming offset [30, 31] is out of the bounds [0, 29] of object 'wifi_result_buffer' with type 'uint8_t[29]' {aka 'unsigned char[29]'} [-Warray-bounds]

### LBM_packet

- [x] at_command.cpp:254:27: warning: comparison of integer expressions of different signedness: 'int32_t' {aka 'long int'} and 'unsigned int' [-Wsign-compare]
- [x] at.cpp:88:26: warning: comparison is always true due to limited range of data type [-Wtype-limits]
- [x] at.cpp:149:13: warning: 'void uint64_to_bytes(uint64_t, uint8_t*)' defined but not used [-Wunused-function]
- [x] at.cpp:210:13: warning: 'void print_d(int32_t)' defined but not used [-Wunused-function]
- [x] at.cpp:215:13: warning: 'void print_u(uint32_t)' defined but not used [-Wunused-function]
- [x] at.cpp:220:16: warning: 'int32_t stringToData(const char*, uint8_t*, uint32_t)' defined but not used [-Wunused-function]
- [x] at.cpp:274:22: warning: 'u8i' is used uninitialized in this function [-Wuninitialized]
- [ ] at.cpp:483:32: warning: format '%hhu' expects argument of type 'unsigned char*', but argument 3 has type 'LoRaMacRegion_t*' {aka 'eLoRaMacRegion*'} [-Wformat=]
- [x] user_stored_data.cpp:102:14: warning: unused variable 'log_len' [-Wunused-variable]
- [x] user_stored_data.cpp:538:14: warning: unused variable 'rlen' [-Wunused-variable]
- [ ] user_stored_data.cpp:655:40: warning: this statement may fall through [-Wimplicit-fallthrough=]
- [x] smtc_hal_mcu.cpp:6:13: warning: 'void vprint1(const char*, va_list)' defined but not used [-Wunused-function]
- [x] smtc_hal_mcu.cpp:39:28: warning: comparison of integer expressions of different signedness: 'uint32_t' {aka 'long unsigned int'} and 'const int32_t' {aka 'const long int'} [-Wsign-compare]
- [x] main_ble.cpp:417:10: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
- [x] main_lbm.cpp:217:29: warning: operation on 'app_task_lora_tx_in' may be undefined [-Wsequence-point]
- [x] main_packet.cpp:121:13: warning: variable 'lorawan_region_sub_band' set but not used [-Wunused-but-set-variable]
- [x] main_track.cpp:34:27: warning: unused variable 'utc_ble' [-Wunused-variable]
- [x] main_sensor.cpp:468:17: warning: 'init_average' defined but not used [-Wunused-variable]
- [x] main_sensor.cpp:468:17: warning: unused variable 'init_average' [-Wunused-variable]
- [x] main_sensor.cpp:469:20: warning: 'index' defined but not used [-Wunused-variable]
- [x] main_sensor.cpp:469:20: warning: unused variable 'index' [-Wunused-variable]
- [x] main_sensor.cpp:522:10: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
- [x] main_sensor.cpp:523:6: warning: unused variable 'i' [-Wunused-variable]
- [x] main_sensor.cpp:524:6: warning: unused variable 'size' [-Wunused-variable]
- [x] main_sensor.cpp:746:41: warning: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
- [x] main_sensor.cpp:753:36: warning: format '%d' expects argument of type 'int', but argument 2 has type 'int32_t' {aka 'long int'} [-Wformat=]
- [x] main_sensor.cpp:910:33: warning: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
- [x] main_sensor.cpp:925:28: warning: format '%d' expects argument of type 'int', but argument 2 has type 'int32_t' {aka 'long int'} [-Wformat=]

### Seeed_Arduino_LIS3DHTR

- [x] LIS3DHTR.cpp:482:13: warning: variable 'data' set but not used [-Wunused-but-set-variable]
- [x] LIS3DHTR.cpp:482:13: warning: variable 'data' set but not used [-Wunused-but-set-variable]

### arduino-core

- [x] SensirionRxFrame.cpp:58:12: warning: 'ret' may be used uninitialized in this function [-Wmaybe-uninitialized]
- [x] SensirionRxFrame.cpp:75:12: warning: 'ret' may be used uninitialized in this function [-Wmaybe-uninitialized]
- [x] SensirionRxFrame.cpp:112:20: warning: 'convert' may be used uninitialized in this function [-Wmaybe-uninitialized]

### Seeed_Arduino_DPS310

- [x] Dps310.cpp:84:13: warning: unused variable 'ret' [-Wunused-variable]
- [x] DpsClass.cpp:171:42: warning: 'raw_val' may be used uninitialized in this function [-Wmaybe-uninitialized]
- [x] DpsClass.cpp:171:42: warning: 'raw_val' may be used uninitialized in this function [-Wmaybe-uninitialized]
- [x] DpsClass.cpp:171:42: warning: 'raw_val' may be used uninitialized in this function [-Wmaybe-uninitialized]

### Grove_Sunlight_Sensor

- [x] Si115X.cpp:15:26: warning: comparison is always false due to limited range of data type [-Wtype-limits]
- [x] Si115X.cpp:124:22: warning: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'unsigned int'} [-Wsign-compare]

```
| Wio_Tracker_1110_Examples | default_firmware.ino                | warnings  | 44.63s |
/home/runner/work/Adafruit_nRF52_Arduino_priv/Adafruit_nRF52_Arduino_priv/libraries/Wio_Tracker_1110_Examples/examples/LoRaWAN/SenseCAP/default_firmware/default_firmware.ino:235:16: warning: format '%d' expects argument of type 'int', but argument 2 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
/home/runner/work/Adafruit_nRF52_Arduino_priv/Adafruit_nRF52_Arduino_priv/libraries/Wio_Tracker_1110_Examples/examples/LoRaWAN/SenseCAP/default_firmware/default_firmware.ino:246:21: warning: unused variable 'counter' [-Wunused-variable]
/home/runner/work/Adafruit_nRF52_Arduino_priv/Adafruit_nRF52_Arduino_priv/libraries/Wio_Tracker_1110_Examples/examples/LoRaWAN/SenseCAP/default_firmware/default_firmware.ino:275:13: warning: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
/home/runner/work/Adafruit_nRF52_Arduino_priv/Adafruit_nRF52_Arduino_priv/libraries/Wio_Tracker_1110_Examples/examples/LoRaWAN/SenseCAP/default_firmware/default_firmware.ino:275:13: warning: format '%u' expects argument of type 'unsigned int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
/home/runner/work/Adafruit_nRF52_Arduino_priv/Adafruit_nRF52_Arduino_priv/libraries/Wio_Tracker_1110_Examples/examples/LoRaWAN/SenseCAP/default_firmware/default_firmware.ino:275:13: warning: format '%u' expects argument of type 'unsigned int', but argument 4 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
/home/runner/work/Adafruit_nRF52_Arduino_priv/Adafruit_nRF52_Arduino_priv/libraries/Wio_Tracker_1110_Examples/examples/LoRaWAN/SenseCAP/default_firmware/default_firmware.ino:323:17: warning: format '%d' expects argument of type 'int', but argument 2 has type 'int32_t' {aka 'long int'} [-Wformat=]
/home/runner/work/Adafruit_nRF52_Arduino_priv/Adafruit_nRF52_Arduino_priv/libraries/Wio_Tracker_1110_Examples/examples/LoRaWAN/SenseCAP/default_firmware/default_firmware.ino:323:17: warning: format '%d' expects argument of type 'int', but argument 3 has type 'int32_t' {aka 'long int'} [-Wformat=]
/home/runner/work/Adafruit_nRF52_Arduino_priv/Adafruit_nRF52_Arduino_priv/libraries/Wio_Tracker_1110_Examples/examples/LoRaWAN/SenseCAP/default_firmware/default_firmware.ino:246:21: warning: 'counter' defined but not used [-Wunused-variable]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_WM1110/src/mw/geolocation_middleware/wifi/src/wifi_middleware.c:711:9: warning: 'memcpy' forming offset [30, 31] is out of the bounds [0, 29] of object 'wifi_result_buffer' with type 'uint8_t[29]' {aka 'unsigned char[29]'} [-Warray-bounds]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/app_param/at_command.cpp:254:27: warning: comparison of integer expressions of different signedness: 'int32_t' {aka 'long int'} and 'unsigned int' [-Wsign-compare]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/app_param/at.cpp:88:26: warning: comparison is always true due to limited range of data type [-Wtype-limits]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/app_param/at.cpp:483:32: warning: format '%hhu' expects argument of type 'unsigned char*', but argument 3 has type 'LoRaMacRegion_t*' {aka 'eLoRaMacRegion*'} [-Wformat=]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/app_param/at.cpp:220:16: warning: 'int32_t stringToData(const char*, uint8_t*, uint32_t)' defined but not used [-Wunused-function]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/app_param/at.cpp:215:13: warning: 'void print_u(uint32_t)' defined but not used [-Wunused-function]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/app_param/at.cpp:210:13: warning: 'void print_d(int32_t)' defined but not used [-Wunused-function]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/app_param/at.cpp:149:13: warning: 'void uint64_to_bytes(uint64_t, uint8_t*)' defined but not used [-Wunused-function]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/app_param/at.cpp:274:22: warning: 'u8i' is used uninitialized in this function [-Wuninitialized]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/app_param/user_stored_data.cpp:102:14: warning: unused variable 'log_len' [-Wunused-variable]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/app_param/user_stored_data.cpp:538:14: warning: unused variable 'rlen' [-Wunused-variable]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/app_param/user_stored_data.cpp:655:40: warning: this statement may fall through [-Wimplicit-fallthrough=]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/common/smtc_hal_mcu.cpp:39:28: warning: comparison of integer expressions of different signedness: 'uint32_t' {aka 'long unsigned int'} and 'const int32_t' {aka 'const long int'} [-Wsign-compare]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/common/smtc_hal_mcu.cpp:6:13: warning: 'void vprint1(const char*, va_list)' defined but not used [-Wunused-function]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/internal/main_ble.cpp:417:10: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/internal/main_lbm.cpp:217:29: warning: operation on 'app_task_lora_tx_in' may be undefined [-Wsequence-point]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/internal/main_lbm.cpp:217:29: warning: operation on 'app_task_lora_tx_in' may be undefined [-Wsequence-point]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/internal/main_packet.cpp:121:13: warning: variable 'lorawan_region_sub_band' set but not used [-Wunused-but-set-variable]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/internal/main_track.cpp:34:27: warning: unused variable 'utc_ble' [-Wunused-variable]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/internal/main_sensor.cpp:468:17: warning: unused variable 'init_average' [-Wunused-variable]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/internal/main_sensor.cpp:469:20: warning: unused variable 'index' [-Wunused-variable]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/internal/main_sensor.cpp:522:10: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/internal/main_sensor.cpp:523:6: warning: unused variable 'i' [-Wunused-variable]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/internal/main_sensor.cpp:524:6: warning: unused variable 'size' [-Wunused-variable]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/internal/main_sensor.cpp:746:41: warning: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/internal/main_sensor.cpp:753:36: warning: format '%d' expects argument of type 'int', but argument 2 has type 'int32_t' {aka 'long int'} [-Wformat=]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/internal/main_sensor.cpp:910:33: warning: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/internal/main_sensor.cpp:925:28: warning: format '%d' expects argument of type 'int', but argument 2 has type 'int32_t' {aka 'long int'} [-Wformat=]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/internal/main_sensor.cpp:469:20: warning: 'index' defined but not used [-Wunused-variable]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/LBM_packet/src/internal/main_sensor.cpp:468:17: warning: 'init_average' defined but not used [-Wunused-variable]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/Seeed_Arduino_LIS3DHTR/src/LIS3DHTR.cpp:482:13: warning: variable 'data' set but not used [-Wunused-but-set-variable]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/Seeed_Arduino_LIS3DHTR/src/LIS3DHTR.cpp:482:13: warning: variable 'data' set but not used [-Wunused-but-set-variable]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/arduino-core/src/SensirionRxFrame.cpp:58:12: warning: 'ret' may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/arduino-core/src/SensirionRxFrame.cpp:75:12: warning: 'ret' may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/arduino-core/src/SensirionRxFrame.cpp:112:20: warning: 'convert' may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/Seeed_Arduino_DPS310/src/Dps310.cpp:84:13: warning: unused variable 'ret' [-Wunused-variable]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/Seeed_Arduino_DPS310/src/DpsClass.cpp:171:42: warning: 'raw_val' may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/Seeed_Arduino_DPS310/src/DpsClass.cpp:171:42: warning: 'raw_val' may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/Seeed_Arduino_DPS310/src/DpsClass.cpp:171:42: warning: 'raw_val' may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/Grove_Sunlight_Sensor/Si115X.cpp:15:26: warning: comparison is always false due to limited range of data type [-Wtype-limits]
/home/runner/.arduino15/packages/Seeeduino/hardware/nrf52/1.1.5/libraries/Grove_Sunlight_Sensor/Si115X.cpp:124:22: warning: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'unsigned int'} [-Wsign-compare]
```

**Comment by matsujirushi** [comment]
https://github.com/Seeed-Studio/Wio_Tracker_1110_Examples/commit/fbd471428887f807b09904a697a9731bb742c4d7

**Comment by matsujirushi** [comment]
https://github.com/Seeed-Studio/Adafruit_nRF52_Arduino/commit/86aa17ec5a52605b231981fbb69c62eca6ac1d56

**Comment by matsujirushi** [comment]
https://github.com/Seeed-Studio/Wio_Tracker_1110_Examples/issues/22
